services:
  unified-backup:
    build:
      context: ./unified-backup
      dockerfile: Dockerfile
    image: local/unified-backup:latest
    container_name: keling-unified-backup
    restart: unless-stopped
    environment:
      TZ: ${TIMEZONE:-Asia/Shanghai}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      # 为 export_browse.py 提供 DB_* 环境变量（与 MYSQL_* 保持一致）
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      MAX_BACKUPS: ${RETENTION_DAYS:-1}
      RESTIC_REPOSITORY: ${RESTIC_REPOSITORY:-/data/repo}
      RESTIC_PASSWORD: ${RESTIC_PASSWORD:-change-me}
      RESTIC_BACKUP_ARGS: ${RESTIC_BACKUP_ARGS:---verbose}
      BROWSE_SOURCE_ROOT: /backup
      BROWSE_OUTPUT_ROOT: /data/browse
      MYSQL_CRON: |
        0 0 * * *
        0 12 * * *
      MEDIA_CRON: |
        30 0 * * *
        30 12 * * *
    volumes:
      - keling-admin-back_backend_media:/backup:ro
      - keling-backup-media:/data
      - keling-backup-mysql:/data/mysql
      - keling-e-drive:/mnt/e-drive
    networks:
      - keling-net
  

networks:
  keling-net:
    external: true
    name: keling-net

volumes:
  keling-admin-back_backend_media:
    external: true
    name: keling-admin-back_backend_media
  keling-backup-media:
    driver: local
  keling-backup-mysql:
    driver: local
  keling-e-drive:
    driver: local